// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_api_schemas from "./routes/api/_api_schemas.ts";
import * as $api_transactions_id_ from "./routes/api/transactions/[id].ts";
import * as $api_transactions_index from "./routes/api/transactions/index.ts";
import * as $api_users_index from "./routes/api/users/index.ts";
import * as $home_index from "./routes/home/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $Chart from "./islands/Chart.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Dashboard from "./islands/Dashboard.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/_api_schemas.ts": $api_api_schemas,
    "./routes/api/transactions/[id].ts": $api_transactions_id_,
    "./routes/api/transactions/index.ts": $api_transactions_index,
    "./routes/api/users/index.ts": $api_users_index,
    "./routes/home/index.tsx": $home_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Chart.tsx": $Chart,
    "./islands/Counter.tsx": $Counter,
    "./islands/Dashboard.tsx": $Dashboard,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
